version: '3'
services:
  mongodb:
    image: 'mongo'
    environment:
      - MONGODB_USERNAME=mongodb_username
      - MONGODB_PASSWORD=mongodb_password
  nginx:
    depends_on:
      - admin_api
      - admin_client
      - user_api
    restart: always
    build: Dockerfile.dev
    context: ./nginx
    ports:
      - "3000:80"
  admin_api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./admin_api
    volumes:
      - /app/node_modules
      - ./admin_api:/app
    environment:
      - MONGODB_NAME=quiz
  admin_client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./admin_client
    volumes:
      - /app/node_modules
      - ./admin_client:/app
  user_api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./user_api
    volumes:
      - /app/node_modules
      - ./user_api:/app
    environment:
      - DBNAME=quiz